apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: space.kubestellar.io
spec:
  latestResourceSchemas:
  - v230912-42dff5c1c.spaceproviderdescs.space.kubestellar.io
  - v230912-42dff5c1c.spaces.space.kubestellar.io
status: {}
